uint32[2] s1upleft
uint32[2] s1upright
uint32[2] s1bottomleft
uint32[2] s1bottomright

uint32[2] s2upleft
uint32[2] s2upright
uint32[2] s2bottomleft
uint32[2] s2bottomright

uint32[2] s3upleft
uint32[2] s3upright
uint32[2] s3bottomleft
uint32[2] s3bottomright

uint32[2] s4upleft
uint32[2] s4upright
uint32[2] s4bottomleft
uint32[2] s4bottomright

uint32[2] s5upleft
uint32[2] s5upright
uint32[2] s5bottomleft
uint32[2] s5bottomright

uint32[2] s6upleft
uint32[2] s6upright
uint32[2] s6bottomleft
uint32[2] s6bottomright

uint32[2] s7upleft
uint32[2] s7upright
uint32[2] s7bottomleft
uint32[2] s7bottomright

uint32[2] s8upleft
uint32[2] s8upright
uint32[2] s8bottomleft
uint32[2] s8bottomright

uint32[2] s9upleft
uint32[2] s9upright
uint32[2] s9bottomleft
uint32[2] s9bottomright

uint32[2] s10upleft
uint32[2] s10upright
uint32[2] s10bottomleft
uint32[2] s10bottomright

uint32[2] s11upleft
uint32[2] s11upright
uint32[2] s11bottomleft
uint32[2] s11bottomright

uint32[2] s12upleft
uint32[2] s12upright
uint32[2] s12bottomleft
uint32[2] s12bottomright

uint32[2] s13upleft
uint32[2] s13upright
uint32[2] s13bottomleft
uint32[2] s13bottomright
