uint32[2] prg1left
uint32[2] prg1right

uint32[2] prg2left
uint32[2] prg2right

uint32[2] prg3left 
uint32[2] prg3right

uint32[2] prg4left
uint32[2] prg4right

uint32[2] prg5left
uint32[2] prg5right

uint32[2] prg6left
uint32[2] prg6right

uint32[2] prg7left
uint32[2] prg7right

uint32[2] prg8left
uint32[2] prg8right

uint32[2] prg9left
uint32[2] prg9right

uint32[2] prg10left
uint32[2] prg10right

uint32[2] prg11left
uint32[2] prg11right

uint32[2] option1left 
uint32[2] option1right

uint32[2] option2left
uint32[2] option2right

uint32[2] option3left
uint32[2] option3right

uint32[2] option4left
uint32[2] option4right
